apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abc-uat-redis
  name: abc-uat-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-uat-redis
  template:
    metadata:
      labels:
        app: abc-uat-redis
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/oneappuat/oneapp-uat-docker-registry/redis-rhel-ubi9:v2
        name: abc-uat-redis
        ports:
        - containerPort: 6379
            name: abc-dev-common-app-properties
        env:
        - name: TZ
          value: Asia/Kolkata
