apiVersion: v1
kind: Service
metadata:
  labels:
    app: abc-ENV-life-insurance-quiz
  name: abc-ENV-life-insurance-quiz
spec:
  type: ClusterIP
  ports:
  - name: abc-ENV-life-insurance-quiz
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: abc-ENV-life-insurance-quiz
