apiVersion: v1
data:
  ABFL_BREWRAPPER_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvYnJld3JhcHBlcg==
  ABFL_CIBILBUREAU_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvY2liaWxnZW5lcmF0aW9u
  ABFL_CREDITDETAILS_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZ2V0Y3JlZGl0b2ZmZXJkZXRhaWxzLw==
  ABFL_D2CPULL_URL: aHR0cHM6Ly9pc3RzLmVxdWlmYXguY28uaW4vY2lyMzYwc2VydmljZS9jaXIzNjByZXBvcnQ=
  ABFL_DIGI_SIGN_POLLING_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZGlnaXNpZ25zdGF0dXM=
  ABFL_DIGI_SIGN_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZGlnaXNpZ24=
  ABFL_EMANDATE_STATUS_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZW1hbmRhdGVzdGF0dXM=
  ABFL_EMANDATE_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZW1hbmRhdGVhdXRo
  ABFL_FETCH_PAN_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZmV0Y2hwYW4=
  ABFL_GENERATE_CCCID_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZ2VuZXJhdGVjY2lk
  ABFL_KYC_CKYC_POLLING_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvY2t5Y3BvbGxpbmc=
  ABFL_KYC_CKYC_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvY2t5Yw==
  ABFL_KYC_DIGILOCKER_POLLING_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZGlnaWxvY2tlcnBvbGxpbmc=
  ABFL_KYC_DIGILOCKER_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZGlnaWxvY2tlcg==
  ABFL_KYC_UNIFIED_POLLING_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvdW5pZmllZGt5Y3N0YXR1cw==
  ABFL_KYC_UNIFIED_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvdW5pZmllZGt5Yw==
  ABFL_LOAN_DISBUREMNET_STATUS_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvbG9hbmRpc2J1cnNlbWVudHN0YXR1cw==
  ABFL_LOAN_DISBUREMNET_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvbG9hbmRpc2J1cnNlbWVudA==
  ABFL_LOANAGREEMENT_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvbG9hbmFncmVlbWVudGdlbmVyYXRpb24=
  ABFL_PENNYDROP_VERIFY_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvcGVubnlkcm9wdmVyaWZ5
  ABFL_REPAYMENT_SCHEDULE_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvcmVwYXltZW50c2NoZWR1bGVrZnM=
  ABFL_SANCTIONLETTER_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvc2FuY3Rpb25sZXR0ZXJnZW5lcmF0aW9u
  ABFL_SEND_OTP_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvc2VuZG90cA==
  ABFL_VERIFY_OTP_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvdmVyaWZ5b3Rw
  ABFL_VERIFY_PAN_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvdmVyaWZ5cGFu
  PL_DISTANCE_ZUMBIO_URL: aHR0cHM6Ly9hcGkuYWJjc2N1YXQuY29tL2FiZmwvZ2V0enVtaWdvZGlzdGFuY2VzdjI=
kind: Secret
metadata:
  name: abc-sit-pl-app-properties
