apiVersion: v1
data:
  DIGITAP_BASIC_AUTH: QmFzaWMgTnpRMk9ERTVOelk2YVhKSmJsWTNibVZQU21RMWNuaGtaVnBZY2preE56aExTM0o1Y0RaQlYxRT0=
  DIGITAP_URL: aHR0cHM6Ly9hcGlkZW1vLmRpZ2l0YXAud29yay9leHBlbnNlX21hbmFnZXIvdjIvZ2V0X3Jlc3BvbnNl
  EQUIFAX_AUTH: Tnpsbk1IRTJPVFEzYVRoa1pURXhOSFF4YUhKc2JHSnFjVGc2TVdvd1luQTBjV1JoTW1WeGJ6Sm5jbWhoWmpKMmEzUnFkbk0wWjNWd1pqVnNkVE56YUhSa1kyNXZOMnByWVc4NU5HNTJjZz09
  EQUIFAX_CLIENTID: NzlnMHE2OTQ3aThkZTExNHQxaHJsbGJqcTg=
  EQUIFAX_CUSTOMER_ID: OTIxNg==
  EQUIFAX_GRANTTYPE: Y2xpZW50X2NyZWRlbnRpYWxz
  EQUIFAX_MEMBER_NUMBER: MDI3RlAxMzg4Mw==
  EQUIFAX_PASSWORD: VzMjUWVpY3NC
  EQUIFAX_PROD: dHJ1ZQ==
  EQUIFAX_PRODUCT_NAME: UENSTFQ=
  PC_AUTHORIZATION_API_KEY: NDhkYzlkMGRmMDQyOTQ1ZWQ4ZmQ3NzRhYmM=
  PC_INITIATE_REQUEST_URL: aHR0cHM6Ly9wcmVwcm9kZml1LnBpcmltaWR0ZWNoLmNvbS9maXUvYXBpL2FiY2RfZml1X3VhdC93ZWIvaW5pdGlhdGUvcGhvbmUtbnVtYmVy
  PC_AA_REDIRECTION_URL: aHR0cHM6Ly9wcmVwcm9kZml1LnBpcmltaWR0ZWNoLmNvbS9maXUvYXBpL2FiY2RfZml1X3VhdC93ZWIvcmVnZW5lcmF0ZS1yZWRpcmVjdGlvbi11cmw=
  PC_FETCH_CONSENT_FLOW_URL: aHR0cHM6Ly9wcmVwcm9kZml1LnBpcmltaWR0ZWNoLmNvbS9maXUvYXBpL2FiY2RfZml1X3VhdC93ZWIvc3RhdHVz
  PC_TEMPLATE_TYPE: VU5ERVJXUklUSU5H
  PC_REDIRECTION_URL: aHR0cHM6Ly9iYXNldXJsLmNvbQ==
  PC_DATA_FETCH_ANALYTICS_URL: aHR0cHM6Ly9wcmVwcm9kZml1LnBpcmltaWR0ZWNoLmNvbS9maXUvYXBpL2FiY2RfZml1X3VhdC93ZWIvZmV0Y2gvYW5hbHl0aWNzL2pzb24=
  EQUIFAX_SCOPE: YjJjL2F1dGg=
  EQUIFAX_SECURITY_CODE: OVFE
  EQUIFAX_SIMULATOR_PRODUCT_NAME_CS01: Q1MwMQ==
  EQUIFAX_SIMULATOR_PRODUCT_NAME_CS02: Q1MwMg==
  EQUIFAX_SIMULATOR_USER_ID: U1RTX1NDUlNNVQ==
  EQUIFAX_TOKEN_URL: aHR0cHM6Ly9hYmZzcy1wcm9kLWFwaS5hdXRoLmFwLXNvdXRoLTEuYW1hem9uY29nbml0by5jb20vb2F1dGgyL3Rva2Vu
  EQUIFAX_URL: aHR0cHM6Ly9hcGkuYWRpdHlhYmlybGFjYXBpdGFsLmNvbS9hYmZsL2QyY3NvZnRwdWxs
  EQUIFAX_USER_ID: U1RTX0FQQ1JMVA==
  FINARKIN_ANALYSIS_RESULT_URL: aHR0cHM6Ly9hcGkuZmluYXJrZWluLmNvbS9mbHV4L3YxL2FiYzEvcnVuL2Zsb3cvYjlkMmVhYWYtMjNiYS00ZTU1LWIxMjUtMzFlOGEwYWJhZWFl
  FINARKIN_ANALYSIS_STATUS_URL: aHR0cHM6Ly9hcGkuZmluYXJrZWluLmNvbS9mbHV4L3YxL2FiYzEvcnVuL2Zsb3cvc3RhdHVzL2I5ZDJlYWFmLTIzYmEtNGU1NS1iMTI1LTMxZThhMGFiYWVhZQ==
  FINARKIN_AUTH_CLIENT_ID: Y2xpZW50LWFiYzEtYThlOTdlOWY=
  FINARKIN_AUTH_CLIENT_SECRET: aVRvVU1oMjM1ZkVXZWFYNjYyUzFhMjc1THdtUTBERDY=
  FINARKIN_AUTH_TOKEN_URL: aHR0cHM6Ly9pZC5maW5hcmtlaW4uY29tL2F1dGgvcmVhbG1zL2ZpbmFya2Vpbi9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC90b2tlbg==
  FINARKIN_FLOW_ID: YjlkMmVhYWYtMjNiYS00ZTU1LWIxMjUtMzFlOGEwYWJhZWFl
  FINARKIN_RUN_ANALYSIS_URL: aHR0cHM6Ly9hcGkuZmluYXJrZWluLmNvbS9mbHV4L3YxL2FiYzEvcnVuL2Zsb3cvYjlkMmVhYWYtMjNiYS00ZTU1LWIxMjUtMzFlOGEwYWJhZWFl
  FINARKIN_WORKSPACE: YWJjMQ==
  GCP_CONFIG_FILE: b25lYXBwcHJvZC0zODgyMTItYWRiMWRiNjdkYWJlLmpzb24=
  GCP_PROJECT_ID: b25lYXBwcHJvZC0zODgyMTI=
  GCP_BUCKET_ID: b25lYXBwLXByb2QtY3JlZGl0dmFzLXJlcG9ydA==
kind: Secret
metadata:
  name: abc-ENV-creditvas-app-properties
