apiVersion: v1
data:
  DB_PASSWORD: QWJjQDJrMjMmJSQ=
  DB_URL: amRiYzpteXNxbDovLzEwLjIxNC4xMjguNzozMzA2L0FCQ0RQUk9EREI/dXNlU1NMPWZhbHNl
  DB_USERNAME: QUJDUFJEX1JX
  REDIS_HOSTNAME: MTAuMTgwLjcuODc=
  REDIS_PORT: NjM3OQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: abc-prod-common-app-properties
