apiVersion: v1
kind: Service
metadata:
  labels:
    app: abc-ENV-health-insurance-calculator
  name: abc-ENV-health-insurance-calculator
spec:
  type: ClusterIP
  ports:
  - name: abc-ENV-health-insurance-calculator
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: abc-ENV-health-insurance-calculator
